# Generated by Django 6.1.1 on 2026-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('position', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Duration to the next airport in minutes')),
                ('next_airport', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
